title: ctf-flags.sh
github_username: xabinapal
description: A collection of CTF writeups with a modern terminal-inspired aesthetic.
url: https://ctf-flags.sh
baseurl: ""

safe: false

markdown: kramdown
theme: null

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml

collections:
  competitions:
    output: true
    permalink: /competitions/:name/
  writeups:
    output: true
    permalink: /competitions/:path/

defaults:
  - scope:
      type: competitions
      path: ""
    values:
      layout: competition

  - scope:
      type: writeups
      path: ""
    values:
      layout: writeup
